on:
  workflow_dispatch:
  schedule:
    - cron:  '*/6 * * * *'

name: Check for KZZ

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      # Use cURL to fetch the given URL, saving the response to `data.json`
      - name: Fetch data
        run: |
          curl 'http://data.10jqka.com.cn/ipo/kzz/' \
          -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
          -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
          -H 'Cache-Control: no-cache' \
          -H 'Connection: keep-alive' \
          -H 'Pragma: no-cache' \
          -H 'Upgrade-Insecure-Requests: 1' \
          -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53' \
          --compressed \
          --insecure
          -o data.json

      - name: Show data
        run: cat data.json

      # Compare the response to the previous run, using a hash of the response as the cache key
      - name: Fetch Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: data.json
          key: ${{ hashFiles('data.json') }}
      

      - name: Notify if data has changed
        if: steps.cache.outputs.cache-hit != 'true'
        run: curl "http://www.pushplus.plus/send?token=ff7273be19b84a01b99f47cedbfb8694&title=%E5%8F%AF%E8%BD%AC%E5%80%BA&&content=kzz"
