name: updateWanIp
on: 
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook-1

  schedule:
    - cron:  '18 19 * * *'
jobs:
  updateWanIp:
    name: updateWanIp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      uses: actions/setup-node@v3
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: install
        
    - name: Cache Node Dependencies
      id: dependencyCache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{runner.OS}}-npm-caches-${{ hashFiles('yarn.lock') }}

    - name: Check Install Dependencies
      if: steps.dependencyCache.outputs.cache-hit != 'true'
      run: yarn


    - name: Goto page and save
      uses: mujo-code/puppeteer-headful@v2
      env:
        CI: 'true'
      with:
        args: npm run updateWanIp
        
