name: ZHIHU
on: 
  workflow_dispatch:
  schedule:
    - cron:  '*/6 * * * *'
jobs:
  zhihuArticleDetect:
    name: zhihuArticleDetect
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      uses: actions/setup-node@v3
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: install
        
    - name: Cache Node Dependencies
      id: dependencyCache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{runner.OS}}-npm-caches-${{ hashFiles('yarn.lock') }}

    - name: Check Install Dependencies
      if: steps.dependencyCache.outputs.cache-hit != 'true'
      run: yarn


    - name: Goto page and save
      uses: mujo-code/puppeteer-headful@v2
      env:
        CI: 'true'
      with:
        args: npm test
        
    - name: Fetch Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: responseData
        key: ${{ hashFiles('responseData') }}
        
    - name: Notify if data has changed
      if: steps.cache.outputs.cache-hit != 'true'
      run: node ./sendRequest.js
