name: ZHIHU
on: 
  workflow_dispatch:

jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      uses: actions/setup-node@v2
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: install
    - name: Install Pupp
      run: npm i
    - name: Goto page and save
      uses: mujo-code/puppeteer-headful@v2
      env:
        CI: 'true'
      with:
        args: npm test
    - name: Fetch Cache
      id: cache
      uses: actions/cache@v2
      with:
        path: responseData
        key: ${{ hashFiles('responseData') }}

    - name: export content
      run: |
        content=$(cat responseData)
        echo $content
        part1="http://www.pushplus.plus/send?token=ff7273be19b84a01b99f47cedbfb8694&title=BANK&&content="
        url=$part1$content
        echo $url
        curl $url
      shell: bash

        

    # - name: Notify if data has changed
    #   if: steps.cache.outputs.cache-hit != 'true'
    #   run: bash ./sendRequest.sh
